// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXW22Lh3DkBjIw3hvP01-EESHseclMVg',
    appId: '1:707318829474:web:85ccf4ebdf2d502fc622fb',
    messagingSenderId: '707318829474',
    projectId: 'pondsafeiot-7026c',
    authDomain: 'pondsafeiot-7026c.firebaseapp.com',
    databaseURL: 'https://pondsafeiot-7026c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-7026c.firebasestorage.app',
    measurementId: 'G-JV8K905GG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwiySQNJqwC6ko9BhY4Qd-h-GnTc7U9Xw',
    appId: '1:707318829474:android:5ed361a9d261dd9cc622fb',
    messagingSenderId: '707318829474',
    projectId: 'pondsafeiot-7026c',
    databaseURL: 'https://pondsafeiot-7026c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-7026c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAv38mBpDzz7uxsdVjtx7oahpM_Tz1Y8',
    appId: '1:707318829474:ios:8d94d72c0df84fa7c622fb',
    messagingSenderId: '707318829474',
    projectId: 'pondsafeiot-7026c',
    databaseURL: 'https://pondsafeiot-7026c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-7026c.firebasestorage.app',
    iosBundleId: 'com.example.pondsafeiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAv38mBpDzz7uxsdVjtx7oahpM_Tz1Y8',
    appId: '1:707318829474:ios:8d94d72c0df84fa7c622fb',
    messagingSenderId: '707318829474',
    projectId: 'pondsafeiot-7026c',
    databaseURL: 'https://pondsafeiot-7026c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-7026c.firebasestorage.app',
    iosBundleId: 'com.example.pondsafeiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXW22Lh3DkBjIw3hvP01-EESHseclMVg',
    appId: '1:707318829474:web:f30296a9935d9cc2c622fb',
    messagingSenderId: '707318829474',
    projectId: 'pondsafeiot-7026c',
    authDomain: 'pondsafeiot-7026c.firebaseapp.com',
    databaseURL: 'https://pondsafeiot-7026c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-7026c.firebasestorage.app',
    measurementId: 'G-J69PFSRQ1R',
  );
}
