// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );q
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSX68XYYHQqoswFcGoRVG_06Ijb-V_6xI',
    appId: '1:901478285419:web:b0ca08510efd41e346312e',
    messagingSenderId: '901478285419',
    projectId: 'pondsafeiot-c370a',
    authDomain: 'pondsafeiot-c370a.firebaseapp.com',
    databaseURL: 'https://pondsafeiot-c370a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-c370a.firebasestorage.app',
    measurementId: 'G-TLY938LKPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIjjCFz1_37oicJ23YGitW96RkIK7nl4',
    appId: '1:901478285419:android:3deead3628d0af3346312e',
    messagingSenderId: '901478285419',
    projectId: 'pondsafeiot-c370a',
    databaseURL: 'https://pondsafeiot-c370a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-c370a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3XOSeDlEPIM40G2mNVU5R0K0Vt6jrSA',
    appId: '1:901478285419:ios:e706bf7ed19ce9ca46312e',
    messagingSenderId: '901478285419',
    projectId: 'pondsafeiot-c370a',
    databaseURL: 'https://pondsafeiot-c370a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-c370a.firebasestorage.app',
    iosBundleId: 'com.example.pondsafeiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3XOSeDlEPIM40G2mNVU5R0K0Vt6jrSA',
    appId: '1:901478285419:ios:e706bf7ed19ce9ca46312e',
    messagingSenderId: '901478285419',
    projectId: 'pondsafeiot-c370a',
    databaseURL: 'https://pondsafeiot-c370a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-c370a.firebasestorage.app',
    iosBundleId: 'com.example.pondsafeiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSX68XYYHQqoswFcGoRVG_06Ijb-V_6xI',
    appId: '1:901478285419:web:59b96a164075d15246312e',
    messagingSenderId: '901478285419',
    projectId: 'pondsafeiot-c370a',
    authDomain: 'pondsafeiot-c370a.firebaseapp.com',
    databaseURL: 'https://pondsafeiot-c370a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pondsafeiot-c370a.firebasestorage.app',
    measurementId: 'G-69RGDB1S66',
  );

}